const dataBase = {
  1: {
    id: 1,
    title: "Чувство жжения за грудиной в ночное время",
    group: "Симптомы в горизонтальном положении",
    groupId: 1,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  2: {
    id: 2,
    title: "Чувство жжения за грудиной в лежачем положении",
    group: "Симптомы в горизонтальном положении",
    groupId: 1,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  3: {
    id: 3,
    title: "Ночные пробуждения с изжогой или боли в груди",
    group: "Симптомы в горизонтальном положении",
    groupId: 1,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  4: {
    id: 4,
    title: "Изжога ночью",
    group: "Симптомы в горизонтальном положении",
    groupId: 1,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  5: {
    id: 5,
    title: "Горечь во рту ночью",
    group: "Симптомы в горизонтальном положении",
    groupId: 1,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  6: {
    id: 6,
    title: "Кислый вкус во рту ночью",
    group: "Симптомы в горизонтальном положении",
    groupId: 1,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  7: {
    id: 7,
    title: "Кашель ночью",
    group: "Симптомы в горизонтальном положении",
    groupId: 1,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  8: {
    id: 8,
    title: "Регургитация ночью",
    group: "Симптомы в горизонтальном положении",
    groupId: 1,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  9: {
    id: 9,
    title: "Жжение за грудиной ночью",
    group: "Симптомы в горизонтальном положении",
    groupId: 1,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  10: {
    id: 10,
    title: "Изжога",
    group: "Изжога",
    groupId: 2,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: true,
  },
  11: {
    id: 11,
    title: "Жжение в горле",
    group: "Изжога",
    groupId: 2,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  12: {
    id: 12,
    title: "Жжение",
    group: "Изжога",
    groupId: 2,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  13: {
    id: 13,
    title: "Жжение во рту",
    group: "Изжога",
    groupId: 2,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  14: {
    id: 14,
    title: "Жжение в груди",
    group: "Изжога",
    groupId: 2,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  15: {
    id: 15,
    title: "Жжение за грудиной",
    group: "Изжога",
    groupId: 2,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  16: {
    id: 16,
    title: "Кислый вкус во рту",
    group: "Изжога",
    groupId: 2,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  17: {
    id: 17,
    title: "Кислый привкус во рту",
    group: "Изжога",
    groupId: 2,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  18: {
    id: 18,
    title: "Кислый вкус во рту особенно после отрыжки или при наклоне вперед",
    group: "Изжога",
    groupId: 2,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  19: {
    id: 19,
    title: "Боль(и) в верхней части живота",
    group: "Изжога",
    groupId: 2,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  20: {
    id: 20,
    title: "Боль(и) в верхних отделах живота",
    group: "Изжога",
    groupId: 2,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  21: {
    id: 21,
    title: "Жжение, поднимающееся вверх по пищеводу",
    group: "Изжога",
    groupId: 2,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  22: {
    id: 22,
    title: "Отрыжка",
    group: "Отрыжка",
    groupId: 3,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: true,
  },
  23: {
    id: 23,
    title: "Отрыжка воздухом после еды",
    group: "Отрыжка",
    groupId: 3,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  24: {
    id: 24,
    title: "Выход воздуха изо рта",
    group: "Отрыжка",
    groupId: 3,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  25: {
    id: 25,
    title: "Движение газов в животе перед отрыжкой",
    group: "Отрыжка",
    groupId: 3,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  26: {
    id: 26,
    title: "Вздутие",
    group: "Отрыжка",
    groupId: 3,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  27: {
    id: 27,
    title: "Ощущение вздутия в животе или грудной клетке перед отрыжкой",
    group: "Отрыжка",
    groupId: 3,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  28: {
    id: 28,
    title: "Неприятный запах изо рта",
    group: "Отрыжка",
    groupId: 3,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  29: {
    id: 29,
    title: "Аэрофагия",
    group: "Отрыжка",
    groupId: 3,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  30: {
    id: 30,
    title: "Эруктация",
    group: "Отрыжка",
    groupId: 3,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  31: {
    id: 31,
    title: "Регургитация",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: true,
  },
  32: {
    id: 32,
    title: "Кислый (при)вкус во рту",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  33: {
    id: 33,
    title: "Горький (при)вкус во рту",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  34: {
    id: 34,
    title: "Горечь во рту",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  35: {
    id: 35,
    title:
      "Кислый или горький (при)вкус во рту, возникающий после отрыжки или при наклоне вперед",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  36: {
    id: 36,
    title: "Возврат/возвращение пищи в горло",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  37: {
    id: 37,
    title: "Возврат/возвращение пищи в горло, сопровождающийся кислым вкусом",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  38: {
    id: 38,
    title: "Ощущение поднимающегося содержимого желудка",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  39: {
    id: 39,
    title: "Болезненное глотание или раздражение горла после возврата кислоты",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  40: {
    id: 40,
    title: "Возврат/возвращение пищи или жидкости в рот",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  41: {
    id: 41,
    title: "Извержение или выброс содержимого желудка",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  42: {
    id: 42,
    title: "Отрыжка с пищей или жидкостью",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  43: {
    id: 43,
    title: "Ощущение подъема пищи или жидкости обратно в горло или рот",
    group: "Срыгивание или регургитация",
    groupId: 4,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  44: {
    id: 44,
    title: "Ощущение кома в горле",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  45: {
    id: 45,
    title:
      "Ощущение кома, инородного тела или стеснения в горле, которое не проходит при глотании",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  46: {
    id: 46,
    title: "Дискомфорт в горле",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  47: {
    id: 47,
    title: "Раздражение в горле",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  48: {
    id: 48,
    title: "Затрудненное глотание из-за чувства кома",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  49: {
    id: 49,
    title: "Трудности при глотании, вызванные ощущением кома в горле",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  50: {
    id: 50,
    title: "Трудно глотать",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  51: {
    id: 51,
    title: "Чувство давления в горле",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  52: {
    id: 52,
    title: "Ощущение давления или стеснения в горле",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  53: {
    id: 53,
    title: "Боль при глотании",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  54: {
    id: 54,
    title: "Дискомфорт в горле при проглатывании",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  55: {
    id: 55,
    title: "Ощущение, что пища 'застревает' в горле",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  56: {
    id: 56,
    title: "Неприятные ощущения или раздражение в горле при проглатывании",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  57: {
    id: 57,
    title: "Ощущение неспособности нормально глотать пищу или жидкость",
    group: "Дисфагия",
    groupId: 6,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  58: {
    id: 58,
    title: "Трудности при глотании",
    group: "Дисфагия",
    groupId: 6,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  59: {
    id: 59,
    title: "Не может проглотить",
    group: "Дисфагия",
    groupId: 6,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  60: {
    id: 60,
    title: "Пища застревает в горле или пищеводе",
    group: "Дисфагия",
    groupId: 6,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  61: {
    id: 61,
    title: "Боль при глотании",
    group: "Дисфагия",
    groupId: 6,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  62: {
    id: 62,
    title: "Дискомфорт при глотании",
    group: "Дисфагия",
    groupId: 6,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  63: {
    id: 63,
    title: "Дополнительные усилия для глотания",
    group: "Дисфагия",
    groupId: 6,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  64: {
    id: 64,
    title: "Нужны дополнительные усилия для глотания",
    group: "Дисфагия",
    groupId: 6,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  65: {
    id: 65,
    title: "Захлебывание",
    group: "Дисфагия",
    groupId: 6,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  66: {
    id: 66,
    title: "Захлебывание или кашель при глотании",
    group: "Дисфагия",
    groupId: 6,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
  67: {
    id: 67,
    title: "Шумное дыхание",
    group: "Одышка",
    groupId: 7,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  68: {
    id: 68,
    title: "Нарушение ритма вдох-выдох",
    group: "Одышка",
    groupId: 7,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  69: {
    id: 69,
    title: "Неритмичное дыхание",
    group: "Одышка",
    groupId: 7,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  70: {
    id: 70,
    title: "Затрудненное дыхание",
    group: "Одышка",
    groupId: 7,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  71: {
    id: 71,
    title: "Учащенное дыхание",
    group: "Одышка",
    groupId: 7,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  72: {
    id: 72,
    title: "Сложно дышать/сложно дышит",
    group: "Одышка",
    groupId: 7,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  73: {
    id: 73,
    title: "Cложно вдохнуть",
    group: "Одышка",
    groupId: 7,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  74: {
    id: 74,
    title: "Сложно выдохнуть",
    group: "Одышка",
    groupId: 7,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  75: {
    id: 75,
    title: "Глубокое дыхание",
    group: "Одышка",
    groupId: 7,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  76: {
    id: 76,
    title: "Интенсивное дыхание",
    group: "Одышка",
    groupId: 7,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  77: {
    id: 77,
    title: "Нехватка вохздуха",
    group: "Одышка",
    groupId: 7,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  78: {
    id: 78,
    title: "Кашель",
    group: "Кашель",
    groupId: 8,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог, Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  79: {
    id: 79,
    title: "Сухой кашель",
    group: "Кашель",
    groupId: 8,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог, Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  80: {
    id: 80,
    title: "Кашель без отхождения мокроты или слизи",
    group: "Кашель",
    groupId: 8,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог, Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  81: {
    id: 81,
    title: "Частый кашель",
    group: "Кашель",
    groupId: 8,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог, Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  82: {
    id: 82,
    title: "Кашель после еды или в положении лежа",
    group: "Кашель",
    groupId: 8,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог, Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  83: {
    id: 83,
    title: "Кашель, сопровождающийся раздражением или дискомфортом в горле",
    group: "Кашель",
    groupId: 8,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог, Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  84: {
    id: 84,
    title: "Ночной кашель",
    group: "Кашель",
    groupId: 8,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог, Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  85: {
    id: 85,
    title:
      "Кашель ночью, который может вызывать пробуждение или затруднения со сном",
    group: "Кашель",
    groupId: 8,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог, Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  86: {
    id: 86,
    title: "Боль в грудной клетке",
    group: "Боль в груди",
    groupId: 9,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  87: {
    id: 87,
    title: "Боль за грудиной",
    group: "Боль в груди",
    groupId: 9,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  88: {
    id: 88,
    title: "Острый или пронзительный дискомфорт в грудной клетке",
    group: "Боль в груди",
    groupId: 9,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  89: {
    id: 89,
    title: "Сдавливающая или давящая боль",
    group: "Боль в груди",
    groupId: 9,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  90: {
    id: 90,
    title: "Сдавливающая или давящая боль в груди",
    group: "Боль в груди",
    groupId: 9,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Кардиолог, Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  91: {
    id: 91,
    title: "Эрозия зубной эмали",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  92: {
    id: 92,
    title: "Повреждение/поражение зубной эмали",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  93: {
    id: 93,
    title: "Истирание или повреждение зубов",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  94: {
    id: 94,
    title: "Усиленная чувствительность зубов",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  95: {
    id: 95,
    title: "Повышенный риск кариеса",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  96: {
    id: 96,
    title: "Частый кариес",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  97: {
    id: 97,
    title: "Потеря блеска зубов",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  98: {
    id: 98,
    title: "Сглаживание поверхности зубов",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  99: {
    id: 99,
    title: "Частые воспаления десен",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  100: {
    id: 100,
    title: "Гингивит",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  101: {
    id: 101,
    title: "Почернение эмали зубов",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  102: {
    id: 102,
    title: "Дентальные эрозии",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  103: {
    id: 103,
    title: "Стоматит",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  104: {
    id: 104,
    title: "Афтозный стоматит",
    group: "Стоматологический синдром",
    groupId: 10,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Стоматолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  105: {
    id: 105,
    title:
      "Одышка, диспноэ, затрудненное дыхание, чувство удушья, нехватка воздуха",
    group: "Астматические симптомы",
    groupId: 11,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  106: {
    id: 106,
    title:
      "Хрипы, свистящее дыхание, свистящие звуки при дыхании, шумное дыхание",
    group: "Астматические симптомы",
    groupId: 11,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  107: {
    id: 107,
    title: "Кашель , сухой кашель, кашель с мокротой, приступы кашля",
    group: "Астматические симптомы",
    groupId: 11,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  108: {
    id: 108,
    title: "Стеснение в груди, чувство давления, стянутость, тяжесть в груди",
    group: "Астматические симптомы",
    groupId: 11,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  109: {
    id: 109,
    title:
      "Утомляемость, слабость - недостаток энергии, частое ощущение усталости, снижение работоспособности",
    group: "Астматические симптомы",
    groupId: 11,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Пульмонолог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  110: {
    id: 110,
    title:
      "Охриплость голоса и дисфония. Голос может звучать хрипло, напряженно или слабо",
    group: "Признаки ЛФР",
    groupId: 12,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  111: {
    id: 111,
    title: "Хронический кашель, усиливающийся утром или после приема пищи",
    group: "Признаки ЛФР",
    groupId: 12,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  112: {
    id: 112,
    title: "Ощущение комка в горле (глобусное ощущение)",
    group: "Признаки ЛФР",
    groupId: 12,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  113: {
    id: 113,
    title: "Хроническая боль в горле без признаков инфекции",
    group: "Признаки ЛФР",
    groupId: 12,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  114: {
    id: 114,
    title: "Носовой затек",
    group: "Признаки ЛФР",
    groupId: 12,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  115: {
    id: 115,
    title: "Затруднения при глотании (дисфагия)",
    group: "Признаки ЛФР",
    groupId: 12,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  116: {
    id: 116,
    title: "Астмаподобные симптомы, такие как свист в груди, одышка или кашель",
    group: "Признаки ЛФР",
    groupId: 12,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Оториноларинголог",
    ph: true,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  117: {
    id: 117,
    title: "Нарушения сна",
    group: "Нарушения сна",
    groupId: 13,
    type: "Внепищеводные",
    typeId: 2,
    doctors: "Психотерапевт",
    ph: false,
    manometry: false,
    radiography: false,
    showOnFront: false,
  },
  118: {
    id: 118,
    title: "Дисфагия",
    group: "Дисфагия",
    groupId: 6,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: true,
  },
  119: {
    id: 119,
    title: "Одинофагия",
    group: "Одинофагия (боли при глотании)",
    groupId: 5,
    type: "Пищеводные",
    typeId: 1,
    doctors: "",
    ph: false,
    manometry: true,
    radiography: true,
    showOnFront: false,
  },
};

const dataBaseJSON = JSON.stringify(dataBase, null, 2);

console.log(dataBaseJSON);